package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SyncProductManageSoap", targetNamespace = "http://tempuri.org/")
public interface SyncProductManageSoap {

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncCrbtProduct")
	@WebResult(name = "syncCrbtProductResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncCrbtProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncCrbtProduct")
	@ResponseWrapper(localName = "syncCrbtProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncCrbtProductResponse")
	public Response syncCrbtProduct(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncCrbtProductEvt event);

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncWirelessProduct")
	@WebResult(name = "syncWirelessProductResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncWirelessProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncWirelessProduct")
	@ResponseWrapper(localName = "syncWirelessProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncWirelessProductResponse")
	public Response syncWirelessProduct(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncWirelessProductEvt event);

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncTagTemplate")
	@WebResult(name = "syncTagTemplateResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncTagTemplate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncTagTemplate")
	@ResponseWrapper(localName = "syncTagTemplateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncTagTemplateResponse")
	public Response syncTagTemplate(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncTagTemplateEvt event);

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncTags")
	@WebResult(name = "syncTagsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncTags", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncTags")
	@ResponseWrapper(localName = "syncTagsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncTagsResponse")
	public Response syncTags(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncTagsEvt event);

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncMaterial")
	@WebResult(name = "syncMaterialResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncMaterial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncMaterial")
	@ResponseWrapper(localName = "syncMaterialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncMaterialResponse")
	public Response syncMaterial(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncMaterialEvt event);

	/**
	 * 
	 * @param event
	 * @return returns org.tempuri.Response
	 */
	@WebMethod(action = "http://tempuri.org/syncCatalogInfo")
	@WebResult(name = "syncCatalogInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "syncCatalogInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncCatalogInfo")
	@ResponseWrapper(localName = "syncCatalogInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncCatalogInfoResponse")
	public Response syncCatalogInfo(
			@WebParam(name = "event", targetNamespace = "http://tempuri.org/") SyncCatalogInfoEvt event);

}
