package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SyncProductManage service = new SyncProductManage();
 * SyncProductManageSoap portType = service.getSyncProductManageSoap();
 * portType.syncCrbtProduct(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SyncProductManage", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.1.224:8088/nivr/SyncProductManageSoap?wsdl")
public class SyncProductManage extends Service {

	private final static URL SYNCPRODUCTMANAGE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.SyncProductManage.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.SyncProductManage.class.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.1.224:8088/nivr/SyncProductManageSoap?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.224:8088/nivr/SyncProductManageSoap?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SYNCPRODUCTMANAGE_WSDL_LOCATION = url;
	}

	public SyncProductManage(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SyncProductManage() {
		super(SYNCPRODUCTMANAGE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"SyncProductManage"));
	}

	/**
	 * 
	 * @return returns SyncProductManageSoap
	 */
	@WebEndpoint(name = "SyncProductManageSoap")
	public SyncProductManageSoap getSyncProductManageSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"SyncProductManageSoap"), SyncProductManageSoap.class);
	}

}
