
package com.sitech.nbc.product.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.sitech.nbc.product.model.xsd.DAlbumInfoEvt;
import com.sitech.nbc.product.model.xsd.Response;
import com.sitech.nbc.product.model.xsd.SyncCatalogInfoEvt;
import com.sitech.nbc.product.model.xsd.SyncCrbtDeployResultEvt;
import com.sitech.nbc.product.model.xsd.SyncCrbtProductEvt;
import com.sitech.nbc.product.model.xsd.SyncMaterialEvt;
import com.sitech.nbc.product.model.xsd.SyncTagTemplateEvt;
import com.sitech.nbc.product.model.xsd.SyncTagsEvt;
import com.sitech.nbc.product.model.xsd.SyncWirelessProductEvt;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "productServicePortType", targetNamespace = "http://server.product.nbc.sitech.com")
@XmlSeeAlso({
    com.sitech.nbc.product.server.ObjectFactory.class,
    com.sitech.nbc.product.model.dalbum_child.xsd.ObjectFactory.class,
    com.sitech.nbc.product.model.xsd.ObjectFactory.class
})
public interface ProductServicePortType {


    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:deployeDAlbum")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "deployeDAlbum", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.DeployeDAlbum")
    @ResponseWrapper(localName = "deployeDAlbumResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.DeployeDAlbumResponse")
    public Response deployeDAlbum(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        DAlbumInfoEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncTagTemplate")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncTagTemplate", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncTagTemplate")
    @ResponseWrapper(localName = "syncTagTemplateResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncTagTemplateResponse")
    public Response syncTagTemplate(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncTagTemplateEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncCatalogInfo")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncCatalogInfo", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCatalogInfo")
    @ResponseWrapper(localName = "syncCatalogInfoResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCatalogInfoResponse")
    public Response syncCatalogInfo(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncCatalogInfoEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncCrbtProduct")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncCrbtProduct", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCrbtProduct")
    @ResponseWrapper(localName = "syncCrbtProductResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCrbtProductResponse")
    public Response syncCrbtProduct(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncCrbtProductEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncTags")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncTags", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncTags")
    @ResponseWrapper(localName = "syncTagsResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncTagsResponse")
    public Response syncTags(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncTagsEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncWirelessProduct")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncWirelessProduct", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncWirelessProduct")
    @ResponseWrapper(localName = "syncWirelessProductResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncWirelessProductResponse")
    public Response syncWirelessProduct(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncWirelessProductEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncMaterial")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncMaterial", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncMaterial")
    @ResponseWrapper(localName = "syncMaterialResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncMaterialResponse")
    public Response syncMaterial(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncMaterialEvt event);

    /**
     * 
     * @param event
     * @return
     *     returns com.sitech.nbc.product.model.xsd.Response
     */
    @WebMethod(action = "urn:syncCrbtDeployResult")
    @WebResult(targetNamespace = "http://server.product.nbc.sitech.com")
    @RequestWrapper(localName = "syncCrbtDeployResult", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCrbtDeployResult")
    @ResponseWrapper(localName = "syncCrbtDeployResultResponse", targetNamespace = "http://server.product.nbc.sitech.com", className = "com.sitech.nbc.product.server.SyncCrbtDeployResultResponse")
    public Response syncCrbtDeployResult(
        @WebParam(name = "event", targetNamespace = "http://server.product.nbc.sitech.com")
        SyncCrbtDeployResultEvt event);

}
