package cn.com.karakal.tyqk.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ManualSendProductDataServiceBean", targetNamespace = "http://ws.tyqk.karakal.com.cn")
public interface ManualSendProductDataServiceBean {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.Response
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "batchAppendSend", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.BatchAppendSend")
	@ResponseWrapper(localName = "batchAppendSendResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.BatchAppendSendResponse")
	public Response batchAppendSend(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<String> arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<Integer> arg3);

	/**
	 * 
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.ExtResponse
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryDataSendStatus", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.QueryDataSendStatus")
	@ResponseWrapper(localName = "queryDataSendStatusResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.QueryDataSendStatusResponse")
	public ExtResponse queryDataSendStatus(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.ProductInfoResponse
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "manualSendProductQueryData", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.ManualSendProductQueryData")
	@ResponseWrapper(localName = "manualSendProductQueryDataResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.ManualSendProductQueryDataResponse")
	public ProductInfoResponse manualSendProductQueryData(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<String> arg2);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.Response
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "manualSendProductData", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.ManualSendProductData")
	@ResponseWrapper(localName = "manualSendProductDataResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.ManualSendProductDataResponse")
	public Response manualSendProductData(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<String> arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<String> arg2);

}
