package cn.com.karakal.tyqk.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ManualSendProductDataService service = new ManualSendProductDataService();
 * ManualSendProductDataServiceBean portType = service.getManualSendProductDataServiceBeanPort();
 * portType.batchAppendSend(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ManualSendProductDataService", targetNamespace = "http://ws.tyqk.karakal.com.cn", wsdlLocation = "http://localhost:8080/tyqk_serverEJB2/ManualSendProductDataService/ManualSendProductDataServiceBean?wsdl")
public class ManualSendProductDataService extends Service {

	private final static URL MANUALSENDPRODUCTDATASERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.karakal.tyqk.ws.ManualSendProductDataService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.karakal.tyqk.ws.ManualSendProductDataService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"http://localhost:8080/tyqk_serverEJB2/ManualSendProductDataService/ManualSendProductDataServiceBean?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/tyqk_serverEJB2/ManualSendProductDataService/ManualSendProductDataServiceBean?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MANUALSENDPRODUCTDATASERVICE_WSDL_LOCATION = url;
	}

	public ManualSendProductDataService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ManualSendProductDataService() {
		super(MANUALSENDPRODUCTDATASERVICE_WSDL_LOCATION,
				new QName("http://ws.tyqk.karakal.com.cn",
						"ManualSendProductDataService"));
	}

	/**
	 * 
	 * @return returns ManualSendProductDataServiceBean
	 */
	@WebEndpoint(name = "ManualSendProductDataServiceBeanPort")
	public ManualSendProductDataServiceBean getManualSendProductDataServiceBeanPort() {
		return super.getPort(new QName("http://ws.tyqk.karakal.com.cn",
				"ManualSendProductDataServiceBeanPort"),
				ManualSendProductDataServiceBean.class);
	}

}
