package cn.com.karakal.tyqk.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ReceiveTyqkDataService", targetNamespace = "http://ws.tyqk.karakal.com.cn")
public interface ReceiveTyqkDataService {

	/**
	 * 
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.Response
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "syncCrbtProduct", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.SyncCrbtProduct")
	@ResponseWrapper(localName = "syncCrbtProductResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.SyncCrbtProductResponse")
	public Response syncCrbtProduct(
			@WebParam(name = "arg0", targetNamespace = "") SyncCrbtProductEvt arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns cn.com.karakal.tyqk.ws.Response
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "syncCrbtDeployResult", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.SyncCrbtDeployResult")
	@ResponseWrapper(localName = "syncCrbtDeployResultResponse", targetNamespace = "http://ws.tyqk.karakal.com.cn", className = "cn.com.karakal.tyqk.ws.SyncCrbtDeployResultResponse")
	public Response syncCrbtDeployResult(
			@WebParam(name = "arg0", targetNamespace = "") SyncCrbtDeployResultEvt arg0);

}
