package cn.com.karakal.tyqk.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ReceiveTyqkDataServiceBean service = new ReceiveTyqkDataServiceBean();
 * ReceiveTyqkDataService portType = service.getReceiveTyqkDataServicePort();
 * portType.syncCrbtProduct(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ReceiveTyqkDataServiceBean", targetNamespace = "http://ws.tyqk.karakal.com.cn", wsdlLocation = "http://211.137.107.18/services/ReceiveTyqkDataService?wsdl")
public class ReceiveTyqkDataServiceBean extends Service {

	private final static URL RECEIVETYQKDATASERVICEBEAN_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.karakal.tyqk.ws.ReceiveTyqkDataServiceBean.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.karakal.tyqk.ws.ReceiveTyqkDataServiceBean.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://211.137.107.18/services/ReceiveTyqkDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://211.137.107.18/services/ReceiveTyqkDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RECEIVETYQKDATASERVICEBEAN_WSDL_LOCATION = url;
	}

	public ReceiveTyqkDataServiceBean(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ReceiveTyqkDataServiceBean() {
		super(RECEIVETYQKDATASERVICEBEAN_WSDL_LOCATION, new QName(
				"http://ws.tyqk.karakal.com.cn", "ReceiveTyqkDataServiceBean"));
	}

	/**
	 * 
	 * @return returns ReceiveTyqkDataService
	 */
	@WebEndpoint(name = "ReceiveTyqkDataServicePort")
	public ReceiveTyqkDataService getReceiveTyqkDataServicePort() {
		return super.getPort(new QName("http://ws.tyqk.karakal.com.cn",
				"ReceiveTyqkDataServicePort"), ReceiveTyqkDataService.class);
	}

}
