package com.ait.com.soap.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CXFFristService service = new CXFFristService();
 * CXFFristService portType = service.getCXFFristServiceImplPort();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CXFFristService", targetNamespace = "http://impl.service.soap.com.ait.com/", wsdlLocation = "http://localhost:8080/CXF_Service/rest/CXFFristService?wsdl")
public class CXFFristService_Service extends Service {

	private final static URL CXFFRISTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ait.com.soap.service.impl.CXFFristService_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ait.com.soap.service.impl.CXFFristService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/CXF_Service/rest/CXFFristService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/CXF_Service/rest/CXFFristService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CXFFRISTSERVICE_WSDL_LOCATION = url;
	}

	public CXFFristService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CXFFristService_Service() {
		super(CXFFRISTSERVICE_WSDL_LOCATION, new QName(
				"http://impl.service.soap.com.ait.com/", "CXFFristService"));
	}

	/**
	 * 
	 * @return returns CXFFristService
	 */
	@WebEndpoint(name = "CXFFristServiceImplPort")
	public CXFFristService getCXFFristServiceImplPort() {
		return super.getPort(new QName("http://impl.service.soap.com.ait.com/",
				"CXFFristServiceImplPort"), CXFFristService.class);
	}

}
